# Database Connection Configuration (esports_tickets is the database name)
spring.datasource.url=jdbc:mysql://localhost:3306/esports_tickets
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA (Hibernate) Configuration: Used for auto-generating tables and logging SQL
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.data.redis.host=localhost
spring.data.redis.port=6379